Kitura/BlueSocket

- README.md
After using the sample `EchoServer` program, I got a build error for `NSString(data: readData, encoding: NSUTF8StringEncoding)` and for `maxBacklog` parameter.
I created a new project with `swift-package-manager` and added `BlueSocket` in dependencies. I'm currently running swift version 3. After changing to `String(data: readData as Data, encoding: String.Encoding.utf8)` and `maxBacklog` to `maxBacklogSize` the example works perfectly.
Solves the sample program build error on swift version 3 related to string encoding
Created a new project and ran the `EchoServer` program. The github repo is [BlueSocketTest](https://github.com/piyushchauhan2011/BlueSocketTest).
```bash
Apple Swift version 3.0 (swiftlang-800.0.33.1 clang-800.0.31)
Target: x86_64-apple-macosx10.9
```
Cheers,
Piyush Chauhan
> Updated the echo server code in readme for swift 3 support.

- Sources/Socket.swift
- Sources/SocketProtocols.swift
The various TCP write functions now return a discardable Int result that is the number of bytes written. These functions no longer throw an error if the write to the socket returned an error of EAGAIN and the socket had been set to non-blocking.
BlueSocket supports non-blocking reads on TCP sockets. However it doesn't support non-blocking writes on TCP sockets as it throws an error if the write returns EAGAIN nor does it return the number of bytes written.
Using Kitura-net's tests
> Add support for non-blocking writes  to TCP sockets

- Sources/Socket.swift
Check endian-ness of host before returning port in hostnameAndPort() function
When returning port in hostnameAndPort() function, it does byte-swap to convert little endian integer to big endian, but this is not necessary in big-endian host, such as zLinux. This patch checks endian-ness of host machine before byte-swapping.
This has been tested on zLinux and x86-64 Linux with `swift test` command.
> Fix endian bug in hostnameAndPort function

- README.md
This is a small update of a small issue I noticed when using the example code. The closing `)` was missing and a couple things in the exclude array didn't make sense. I can add them back if I'm missing their meaning.
> Updated example Package.swift code in README

- BlueSocket.xcodeproj/project.pbxproj
A project setting in Xcode standardizes the use of tabs instead of spaces for indentation across all files.
A single line changed in `project.pbxproj` to change the project settings. Also found in Xcode by clicking on the project in the Project navigator, and then selecting "Tabs" in the Text Settings pane in the File inspector.
When I began attempting to contribute, my editor was using spaces instead of tabs. I changed the project settings and figured this would be a useful change for all contributors.
No tests, no code changes.
> Change project settings so that indentation uses tabs

- Sources/Socket.swift
This change changes the `MARK` heading for one of the initializers, removing the `MARK` for public lifecycle methods since nothing under that header qualified.
Since both `init` methods are private, and `deinit` is never called explicitly anyway, there shouldn't
really be any public lifecycle methods. Creation is handled by the public `create` class functions. I changed the `MARK: -- Public` at the top of the lifecycle methods section to `Private` from `Public`, deleted the `MARK: -- Private` a few lines down, and moved the `deinit` method to the bottom of the initializers.
This is simply a change to keep the implementation in line with the documentation. The initializer is marked private and the documentation
No new functionality has been added, so coverage is provided by existing tests.
> Move private initializer under proper heading

- Sources/Socket.swift
- Tests/SocketTests/SocketTests.swift
This PR adds a `testReadWriteUDP` test, as well as several helper functions.
This PR adds new methods in `SocketTests.swift` as follows:
`launchUDPHelper` spawns a thread containing a UDP server which will listen on port 1337 and respond to one packet sent.
`runUDPHelper` is the method which is actually run in the separate thread.
`testReadWriteUDP` is the actual tester method, which launches the helper, writes to the port, and then reads from the port.
Additionally, this PR adds a helper `init` in `Address` for creating an address from a hostname and port.
Testing the UDP support is important and should be implemented ASAP. Additionally, since UDP is connectionless, we should have a method for easily creating `Address` objects on the fly.
Ran all tests in Xcode.
> Add tests and helper functions for testing UDP read/write

- BlueSocket.xcodeproj/xcshareddata/xcschemes/Socket-iOS.xcscheme
- BlueSocket.xcodeproj/xcshareddata/xcschemes/Socket.xcscheme
This PR shares the schemes `Socket` and `Socket-iOS` for use with [Carthage](https://github.com/Carthage/Carthage).
This PR is equivalent to opening the 'Manage Schemes' pane in Xcode and selecting the 'Shared' checkbox next to the two schemes in the project.
[Issue #29](https://github.com/IBM-Swift/BlueSocket/issues/29)
I successfully managed to add Jumhyn/BlueSocket as a dependency in a test project of mine. Should confirm with the issue's original author to confirm that this resolves it.
> Share schemes for Carthage support

- Sources/Socket.swift
Added comment to remind people that the Unit tests can fail in Xcode if breakpoints are active
This might save someone (in addition to me) time.  
It's just a comment.
> Comment only change

- Sources/Socket.swift
This change always sets the `MSG_NOSIGNAL` flag when writing to a socket, rather than only when the socket `isListening`.  This avoids an unexpected process exit if a `SIGPIPE` occurs.
I was investigating a problem where Kitura occasionally exits with no error message when I drive load.  I checked the return code, which was 141 (128 + 13 which is `SIGPIPE`).  It seems we do not handle the `SIGPIPE`, but nor do we suppress it.
This is intended to fix IBM-Swift/Kitura#965
The Socket tests passed.
Kitura works correctly under load, and now correctly logs a `Broken pipe` error, rather than exiting.
> Always set MSG_NOSIGNAL to avoid process exit due to SIGPIPE

- Sources/Socket.swift
Swift is now a bit stricter in terms of output of optional strings and
chaining of types which are not 100% the same (like Int32 vs Int).
> Fix warnings under Swift 3.1

- Sources/Socket.swift
Memory leak of `addrinfo` allocation present every time `UnsafeMutablePointer<addrinfo>.allocate(capacity: 1)` is called. Every call leaks an additional 48 bytes.
`getaddrinfo()` handles memory allocation to the pointer which is released upon `freeaddrinfo()` however the original allocation from `.allocate(capacity:)` is unallocated and leaked (ARC is not responsible for deallocation of pointers).
Leak is present when run through Xcode Instruments. With pull changes, Instruments no longer reports leak.
> Memory leak from address pointer allocation 

- Sources/Socket.swift
Enabling `IPV6_V6ONLY` on ipv6 listening sockets allows sharing the port with ipv4. This allows one for example to listen on both ipv4 and ipv6 on port 8000.
Tested on macOS 10.12.3 and Ubuntu 16.04.
> Allow port sharing between ipv4 and ipv6

- Sources/Socket.swift
Follow-up on #60; need to set SO_REUSEPORT in order to share (UDP) ports on OSX.
Tested on macOS 10.12.4 and Ubuntu 16.04.
> Set SO_REUSEPORT for port sharing on OSX

- .gitignore
- Sources/SocketUtils.swift
https://swift.org/download/#snapshots
In this snapshot (which I am using to test new JSONEncoder features), `Int` and `Int32` cannot be `|`'d. So I am casting `mask` to `Int32`.
Tested on macOS Xcode 8.3.2 toolchain, 3.1.1 RELEASE, and the trunk dev snapshot aforementioned. Not tested in Linux.
> Fix issue in Swift trunk dev 5/10 snapshot

- BlueSocket.podspec
Allow Podspec to compile for watchOS and tvOS too
Please do a "pod trunk push" after merging the changes (will possibly need a version bump too)
> Update podspec to allow for watchOS and tvOS too

- Sources/Socket.swift
Fixes `EXC_BAD_ACCESS` for UNIX socket protocol on Mac.
In `Signature.init?(socketType:proto:path)`, the copying of the bytes from the provided path to the `sockaddr_un.sun_path` C struct field was done using `strncpy` on a pointer returned by `withCString`. For some reason, while this worked fine in `BlueSocket` tests, this fails with `EXC_BAD_ACCESS` on return of that method when called from an Xcode project using BlueSocket as embedded binary on Mac.
Copying the bytes using `UnsafeMutableBufferPointer` to wrap the `sockaddr_un.sun_path` field fixes the issue.
See #68 
Since there were already UNIX Socket tests in BlueSocket and those were passing fine on my Macbook Pro (macOS 10.12.5), I created a separate minimal Xcode project that calls BlueSocket as Embedded Framework. This does …
> Fix unix socket on Mac / embedded library in Xcode. Fixes #68.

- Sources/Socket/Socket.swift
I have introduced an optional parameter `invokeDelegate` to `acceptClientConnection()`, that can be used to defer the invocation of `delegate?.onAccept(socket)`.
A new function, `invokeDelegateOnAccept(socket)` is introduced to perform the call to the delegate, which will either be called by `acceptClientConnection(invokeDelegate: true)` (equivalent to the previous behaviour), or by the application directly following a call to `acceptClientConnection(invokeDelegate: false)`.
The delegate.onAccept() function may block until the client transmits the SSL handshake.  In the case of a badly behaved client (trivially, `telnet localhost <ssl port>`), this could be indefinite.
Since the only way for the application to know whether an incoming connection is available to be accepted is to block on …
> Enable decoupling of acceptClientConnection and delegate.onAccept

- Sources/Socket/Socket.swift
- Sources/Socket/SocketUtils.swift
asAddr funcs were passing unsafe pointers outside of the callbacks in which try should be used
Using callback to make all the access within these callbacks
Fixes bug where IPv6 address was 'cast' to sockaddr but actually was zero'd beyond the length of sockaddr_in and packets written to the wrong address
- [N/A] If applicable, I have updated the documentation accordingly.
- [N/A] If applicable, I have added tests to cover my changes.
> Remove unsafe access to Socket.Address

- Sources/Socket/Socket.swift
- Sources/Socket/SocketUtils.swift
- `fd_set` API is now much nicer and will compile about as close to the C implementation as we can get— especially on release builds, with compiler inlining.
- Socket structure's `readBuffer` now initializes all its bytes to zero, not just the first.
- More idiomatic/concise return expression in `Socket.wait(for:timeout:waitForever:)` (don't build an output array manually, we have `filter(_:)` for that).
- Various non-Linux code to set the `SO_NOSIGPIPE` option has been tucked into a private function now, still containing the compilation conditional. It's a no-op on Linux, and will be inlined by the compiler (since it's private) and the calling code looks much more straightforward.
- BUGFIX: calls to `gai_strerror(_:)` take the result of the `getaddrinfo()` call as a parameter, NOT …
> A few cleanups and one bug fix:

- Sources/Socket/Socket.swift
- Sources/Socket/SocketUtils.swift
The implementation from the prior pull request now runs happily without corrupting the stack.
I'm calculating the size of the Darwin fd_set correctly now— dividing the `__DARWIN_FD_SET_SIZE` bit-count by the number of *bits* in an `Int32` rather than the stride size (number of *bytes*).
This fixes the crash in #110 properly while keeping the optimized fd_set implementation.
The updated unit tests which caught the original error now pass, and I've verified personally that the implementation does the right thing now, setting the expected bits in the bitfield.
> Fixed the bug in the new fd_set implementation on macOS.

- Sources/Socket/Socket.swift
- Sources/Socket/SocketUtils.swift
- Tests/SocketTests/SocketTests.swift
- Now uses an unsigned type to perform the bit-shift operation and then casts to signed type using `init(bitPattern:)`.
- Added a unit test case which ensures fd values from zero to (arbitrarily) 128 can all be inserted and removed from the` fd_set`.
This fixes the `fd_set` component of issue #120.
Unit test added to verify that the new code works (and which caused the old code to crash in the same manner as described in issue #120).
> Fixed a bit-addressing error in fd_set implementation.

- Sources/Socket/SocketUtils.swift
Fix for big endian machines.
fd_set is defined as 16 64-bit integers in a 64-bit linux machine. Since this package accesses fd_set per 32 bits, endianess needs to be taken aware to calculate the index.
Now, swift is running on IBM mainframe (https://www.ibm.com/developerworks/downloads/r/toolkitforswift/). This fix is essential for Kitura to run on a big endian machine with SSL.
Ran all of the tests on a s390x machine. Results are as follows. Test failures were reduced from 8 to 6.
```
Compile Swift Module 'Socket' (3 sources)
Linking ./.build/s390x-unknown-linux/debug/SocketPackageTests.xctest
Test Suite 'All tests' started at 2018-04-09 10:32:03.293
Test Suite 'debug.xctest' started at 2018-04-09 10:32:03.294
Test Suite 'SocketTests' started at 2018-04-09 10:32:03.294
Test Case …
```
> Endian fix

- Sources/Socket/Socket.swift
If I'm not mistaken, in order to receive an UDP datagram from a specific other party, one currently needs to listen on a specific port and filter out messages from unwanted senders. E.g.
```
let socket = try Socket.create(family: .inet, type: .datagram, proto: .udp)
var message = Data()
repeat {
let (size, sender) = try socket.listen(forMessage: &message, on: 8053, maxBacklogSize: 0)
} while sender != bob
```
However using `connect (2)` this should be as simple as:
```
let socket = try Socket.create(family: .inet, type: .datagram, proto: .udp)
try socket.connect(to: bob.ip, port: bob.port)
var message = Data()
try socket.readDatagram(into: &message)
```
Limited tests on macOS; stepping through debugger to find the problem when trying to connect to UDP sockets.
Are any of the above …
> Make `connect()` work for UDP sockets as well

- Sources/Socket/Socket.swift
Only initialize the first byte of `readBuffer` instead of zeroing the whole buffer.
Currently, before we read from the socket we call `readBuffer.initialize(repeating: 0, count: readBufferSize)` which zeroes out the memory in `readBuffer`.
I don't believe this is necessary because the buffer is about to be overwritten with bytes from the wire anyway, and once that has happened we then copy the read bytes into `readStorage`.
This PR changes the code so we use `initialize(to:)` instead, so only the first byte is zeroed. We do have to call `initialize()` (we can't just remove it completely) but it's cheaper to only initialize one byte.
I've recently been analysing Kitura performance, and the cost of `Socket.readDataIntoStorage()` is significant in debug mode. Most of this is zeroing out the …
> perf: improve read throughput in debug mode

- Sources/Socket/Socket.swift
Allows to create a signature from an Address object and still have a hostname.
The first commit just adds creation of Socket with an Address using the enums for socketType and protocol
The second one rearranges `func connect(using` so that if an address is in the signature this is used for the connection. It also only converts that address back to a hostname if it wasn't included in the Signature.
Previously this would have used the hostname and ignored the address - note this cannot change any existing code because before it wasn't possible to create a Signature with both address and hostname.
I also think its a bit clearly whats going on in the function as before the ordering of checks was complicated with nested ifs and guards.
There are a couple of bonus commits :)
- 114f6b9 updates …
> Improve using Signature to connect socket

- README.md
Remove all IBM references from the readme to fix broken links. Should we also remove the CLA references from the PR template and the CLA bot?
Some links are broken due to the repo name changing
N/A
> Remove IBM references from README

- .gitignore
- Package.swift
Fix warnings due to improper exclusion in Package.swift file.
> Fix warnings due to improper exclusion; update gitignore
